//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyVersion("7.5.375.290")]
[assembly: AssemblyInformationalVersion("7.5.375")]
[assembly: AssemblyFileVersion("7.5.375.290")]
[assembly: AssemblyCopyright("Copyright United Technologies Corporation")]
[assembly: AssemblyCompany("UTC Fire & Security Americas Corporation, Inc.")]


